import { Badge } from '@/components/ui/badge';
import { Band } from '@/components/ps/band';
import { SectionHeader } from '@/components/ps/section-header';
import { Lattice, LatticeCell } from '@/components/ps/lattice';
import { FileSearch, TestTube2, Split, Trash2, Database, Undo2 } from 'lucide-react';

const principles = [
  {
    index: '01',
    icon: FileSearch,
    title: 'Map before you move',
    body: 'Nothing gets ported until I can show you what it does today. The inventory is the deliverable that makes everything after it predictable.'
  },
  {
    index: '02',
    icon: TestTube2,
    title: 'Tests come from production, not imagination',
    body: 'Characterization tests are generated by replaying real recorded traffic against the legacy system. Bug-for-bug parity is the default; every intentional deviation is written down and approved.'
  },
  {
    index: '03',
    icon: Trash2,
    title: 'Delete before you translate',
    body: 'Access logs reliably show that a meaningful share of a legacy codebase is dead. Porting dead code is the most expensive way to keep it.'
  },
  {
    index: '04',
    icon: Database,
    title: 'One migration at a time',
    body: 'Language, framework, database and cloud provider are four separate migrations. Bundling them multiplies the risk instead of adding it. The data layer usually stays put.'
  },
  {
    index: '05',
    icon: Split,
    title: 'Shadow traffic before real traffic',
    body: 'The new service runs alongside the old one against live requests, returning nothing, while a harness diffs every response pair. Disagreements are found by machines, not by customers.'
  },
  {
    index: '06',
    icon: Undo2,
    title: 'Keep the rollback warm',
    body: 'Traffic shifts by percentage with the legacy fleet still running. The old system stays up until the new one has a full billing cycle of clean production behaviour behind it.'
  }
];

const paths = [
  'Java → Python',
  'Java → TypeScript',
  '.NET Framework → .NET / Python',
  'Ruby on Rails → Python / TypeScript',
  'PHP → Python',
  'Perl → Python',
  'AngularJS → React',
  'On-prem → AWS',
  'EC2 → Fargate / ECS',
  'Monolith → services',
  'Oracle → Postgres',
  'Stored procedures → application code'
];

export function Approach() {
  return (
    <Band className="pt-0 pb-16 md:pt-0 md:pb-20">
      <SectionHeader label="The method" />
      <div className="mt-10 max-w-[68ch]">
        <h2 className="text-h2">AI writes fast. The process is what makes it safe.</h2>
        <p className="mt-3.5 text-graphite-500">
          Handing a legacy codebase to a model and shipping what comes out is how migrations
          fail loudly. These are the rules that make the speed usable.
        </p>
      </div>

      <Lattice className="mt-10 md:grid-cols-2 lg:grid-cols-3">
        {principles.map((principle) => (
          <LatticeCell
            key={principle.index}
            index={principle.index}
            icon={principle.icon}
            title={principle.title}
          >
            {principle.body}
          </LatticeCell>
        ))}
      </Lattice>

      <div className="mt-14 border-t border-rule pt-10">
        <span className="ps-label text-graphite-500">Migrations I take on</span>
        <div className="mt-5 flex flex-wrap gap-1.5">
          {paths.map((path) => (
            <Badge key={path}>{path}</Badge>
          ))}
        </div>
        <p className="mt-5 max-w-[68ch] text-graphite-500">
          If your stack is not on this list, it is almost certainly still in scope. The method
          does not depend on the source language — it depends on being able to read the old
          system and replay its traffic.
        </p>
      </div>
    </Band>
  );
}
