'use client';

import { motion } from 'motion/react';
import { Badge } from '@/components/ui/badge';
import { FileSearch, TestTube2, Split, Trash2, Database, Undo2 } from 'lucide-react';

const principles = [
  {
    icon: FileSearch,
    title: 'Map before you move',
    description:
      'Nothing gets ported until we can show you what it does today. The inventory is the deliverable that makes everything after it predictable.',
  },
  {
    icon: TestTube2,
    title: 'Tests come from production, not from imagination',
    description:
      'Characterization tests are generated by replaying real recorded traffic against the legacy system. Bug-for-bug parity is the default; every intentional deviation is written down and approved.',
  },
  {
    icon: Trash2,
    title: 'Delete before you translate',
    description:
      'Access logs reliably show that a meaningful share of a legacy codebase is dead. Porting dead code is the most expensive way to keep it.',
  },
  {
    icon: Database,
    title: 'One migration at a time',
    description:
      'Language, framework, database, and cloud provider are four separate migrations. Bundling them multiplies the risk instead of adding it. The data layer usually stays put.',
  },
  {
    icon: Split,
    title: 'Shadow traffic before real traffic',
    description:
      'The new service runs alongside the old one against live requests, returning nothing, while a harness diffs every response pair. Disagreements are found by machines, not by customers.',
  },
  {
    icon: Undo2,
    title: 'Keep the rollback warm',
    description:
      'Traffic shifts by percentage with the legacy fleet still running. The old system stays up until the new one has a full billing cycle of clean production behavior behind it.',
  },
];

const paths = [
  'Java → Python',
  'Java → TypeScript',
  '.NET Framework → .NET / Python',
  'Ruby on Rails → Python / TypeScript',
  'PHP → Python',
  'Perl → Python',
  'AngularJS → React',
  'On-prem → AWS',
  'EC2 → Fargate / ECS',
  'Monolith → services',
  'Oracle → Postgres',
  'Stored procedures → application code',
];

export function Approach() {
  return (
    <section className="py-20 px-6 bg-muted/30">
      <div className="max-w-6xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="text-center mb-14 space-y-4"
        >
          <h2 className="text-4xl">AI writes fast. The process is what makes it safe.</h2>
          <p className="text-muted-foreground max-w-2xl mx-auto">
            Handing a legacy codebase to a model and shipping what comes out is how
            migrations fail loudly. These are the rules that make the speed usable.
          </p>
        </motion.div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6 mb-16">
          {principles.map((principle, index) => (
            <motion.div
              key={principle.title}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: index * 0.08 }}
              className="p-6 bg-card rounded-xl border border-border space-y-3"
            >
              <div className="w-12 h-12 bg-cyan-500/10 rounded-lg flex items-center justify-center">
                <principle.icon className="w-6 h-6 text-cyan-500" />
              </div>
              <h3>{principle.title}</h3>
              <p className="text-muted-foreground">{principle.description}</p>
            </motion.div>
          ))}
        </div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="text-center space-y-6"
        >
          <h3 className="text-2xl">Migrations we take on</h3>
          <div className="flex flex-wrap gap-2 justify-center max-w-4xl mx-auto">
            {paths.map((path) => (
              <Badge key={path} variant="secondary" className="px-3 py-1.5">
                {path}
              </Badge>
            ))}
          </div>
          <p className="text-muted-foreground max-w-2xl mx-auto">
            If your stack is not on this list, it is almost certainly still in scope.
            The method does not depend on the source language — it depends on being
            able to read the old system and replay its traffic.
          </p>
        </motion.div>
      </div>
    </section>
  );
}
